name: FinanceApp
options:
  bundleIdPrefix: com.financeapp
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15"
  groupSortPosition: top
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"

targets:
  FinanceApp:
    type: application
    platform: iOS
    sources:
      - path: FinanceApp
    settings:
      base:
        INFOPLIST_FILE: FinanceApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.financeapp.tracker
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: false
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGNING_ALLOWED: "NO"
        DEVELOPMENT_TEAM: ""
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_EMIT_LOC_STRINGS: "YES"
        IPHONEOS_DEPLOYMENT_TARGET: "16.0"
